version: '3.4'
services:
  traefik:
    image: 'traefik:v2.3'
    container_name: traefik
    ports:
      - '80:80'
      - '8080:8080'
    labels:
      - "traefik.enable=true"
    volumes:
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./config/provider.yml:/traefik/provider.yml:ro"
    networks:
      - traefik

  python-web1:
    image: python:3.10.0a2
    container_name: python-test1
    command: ["python3", "-m", "http.server", "--directory", "/data", "8000"]
    volumes:
      - "./data/test1:/data/"
    labels:
      - "traefik.enable=true"
    networks:
      - traefik
  
  python-web2:
    image: python:3.10.0a2
    container_name: python-test2
    command: ["python3", "-m", "http.server", "--directory", "/data", "7000"]
    volumes:
      - "./data/test2:/data/"
    labels:
      - "traefik.enable=true"
    networks:
      - traefik

  python-web3:
    image: python:3.10.0a2
    container_name: python-test3
    command: ["python3", "-m", "http.server", "--directory", "/data", "8001"]
    volumes:
      - "./data/test3:/data/"
    labels:
      - "traefik.enable=true"
    networks:
      - traefik  

networks:
  traefik:
    external: true